#


#### $ uv pip list
#### Package             Version
#### ------------------- -----------
#### joblib              1.5.3
#### numpy               2.4.2
#### pandas              3.0.1
#### pyopengl            3.1.10
#### pyopengl-accelerate 3.1.10
#### python-dateutil     2.9.0.post0
#### scikit-learn        1.8.0
#### scipy               1.17.1
#### six                 1.17.0
#### threadpoolctl       3.6.0


#### $ pip list
#### Package                            Version
#### ---------------------------------- ----------------
#### anyio                              4.4.0
#### apt-clone                          0.2.1
#### apturl                             0.5.2
#### argon2-cffi                        23.1.0
#### argon2-cffi-bindings               21.2.0
#### arrow                              1.3.0
#### astroid                            4.0.2
#### asttokens                          2.4.1
#### async-lru                          2.0.4
#### async-timeout                      4.0.1
#### attrs                              24.2.0
#### autopep8                           2.0.4
#### babel                              2.16.0
#### beautifulsoup4                     4.10.0
#### black                              25.12.0
#### bleach                             6.1.0
#### blinker                            1.8.2
#### Brlapi                             0.8.3
#### Brotli                             1.0.9
#### catfish                            4.16.4
#### ccsm                               0.9.14.1
#### certifi                            2020.6.20
#### cffi                               1.17.0
#### chardet                            4.0.0
#### charset-normalizer                 3.3.2
#### cliapp                             1.20180812.1
#### click                              8.1.7
#### cloudpickle                        3.0.0
#### cmdtest                            0.32+git
#### colorama                           0.4.4
#### comm                               0.2.2
#### command-not-found                  0.3
#### compizconfig-python                0.9.14.1
#### configobj                          5.0.6
#### contourpy                          1.3.0
#### cryptography                       3.4.8
#### cupshelpers                        1.0
#### cycler                             0.12.1
#### dash                               2.17.1
#### dash-bootstrap-components          1.6.0
#### dash-core-components               2.0.0
#### dash-html-components               2.0.0
#### dash-table                         5.0.0
#### dask                               2024.8.2
#### dbus-python                        1.2.18
#### debugpy                            1.8.5
#### decorator                          5.1.1
#### defer                              1.0.6
#### defusedxml                         0.7.1
#### dill                               0.4.0
#### distro                             1.7.0
#### docker                             5.0.3
#### docker-compose                     1.29.2
#### dockerpty                          0.4.1
#### docopt                             0.6.2
#### docstring-to-markdown              0.17
#### docutils                           0.17.1
#### eclipse-zenoh                      1.5.0
#### evdev                              1.4.0
#### exceptiongroup                     1.2.2
#### executing                          2.0.1
#### eyeD3                              0.8.10
#### fastjsonschema                     2.20.0
#### filelock                           3.6.0
#### flake8                             7.1.2
#### Flask                              3.0.3
#### FMPy                               0.3.21
#### fonttools                          4.53.1
#### fqdn                               1.5.1
#### fsspec                             2024.6.1
#### glfw                               2.10.0
#### grpcio                             1.30.2
#### h11                                0.14.0
#### html5lib                           1.1
#### httpcore                           1.0.5
#### httplib2                           0.20.2
#### httpx                              0.27.2
#### idna                               3.3
#### ifaddr                             0.1.7
#### IMDbPY                             2021.4.18
#### importlib_metadata                 8.4.0
#### ipykernel                          6.29.5
#### ipython                            8.27.0
#### isoduration                        20.11.0
#### isort                              5.6.4
#### itsdangerous                       2.2.0
#### jedi                               0.19.1
#### jeepney                            0.7.1
#### Jinja2                             3.1.4
#### json5                              0.9.25
#### jsonpointer                        3.0.0
#### jsonschema                         4.23.0
#### jsonschema-specifications          2023.12.1
#### jupyter_client                     8.6.2
#### jupyter_core                       5.7.2
#### jupyter-events                     0.10.0
#### jupyter-lsp                        2.2.5
#### jupyter_server                     2.14.2
#### jupyter_server_terminals           0.5.3
#### jupyterlab                         4.2.5
#### jupyterlab_pygments                0.3.0
#### jupyterlab_server                  2.27.3
#### kaleido                            0.2.1
#### keyring                            23.5.0
#### kiwisolver                         1.4.5
#### language-selector                  0.1
#### lark                               1.2.2
#### launchpadlib                       1.10.16
#### lazr.restfulclient                 0.14.4
#### lazr.uri                           1.0.6
#### lazy-object-proxy                  0.0.0
#### libvirt-python                     8.0.0
#### locket                             1.0.0
#### logilab-common                     1.8.2
#### louis                              3.20.0
#### lxml                               5.3.0
#### macaroonbakery                     1.3.1
#### Mako                               1.1.3
#### Markdown                           3.3.6
#### MarkupSafe                         2.1.5
#### matplotlib                         3.9.2
#### matplotlib-inline                  0.1.7
#### mccabe                             0.7.0
#### meld                               3.20.4
#### menulibre                          2.2.2
#### mistune                            3.0.2
#### more-itertools                     8.10.0
#### msgpack                            1.0.8
#### mugshot                            0.4.3
#### multipledispatch                   1.0.0
#### mutagen                            1.45.1
#### mypy                               0.942
#### mypy-extensions                    0.4.3
#### natsort                            8.0.2
#### nbclient                           0.10.0
#### nbconvert                          7.16.4
#### nbformat                           5.10.4
#### nest-asyncio                       1.6.0
#### netaddr                            0.8.0
#### netifaces                          0.11.0
#### notebook                           7.2.2
#### notebook_shim                      0.2.4
#### numpy                              2.1.0
#### oauthlib                           3.2.0
#### onboard                            1.4.1
#### overrides                          7.7.0
#### packaging                          24.1
#### PAM                                0.4.2
#### pandas                             2.3.3
#### pandocfilters                      1.5.1
#### parso                              0.8.4
#### partd                              1.4.2
#### pathspec                           0.12.1
#### pexpect                            4.8.0
#### Pillow                             9.0.1
#### pip                                22.0.2
#### platformdirs                       4.2.2
#### plotly                             5.24.0
#### pluggy                             1.6.0
#### prometheus_client                  0.20.0
#### prompt_toolkit                     3.0.47
#### protobuf                           3.12.4
#### psutil                             5.9.0
#### ptyprocess                         0.7.0
#### pure_eval                          0.2.3
#### pycairo                            1.20.1
#### pycodestyle                        2.12.1
#### pycparser                          2.22
#### pycryptodomex                      3.11.0
#### pycups                             2.0.1
#### pycurl                             7.44.1
#### pydocstyle                         6.3.0
#### pyelftools                         0.27
#### pyflakes                           3.2.0
#### Pygments                           2.11.2
#### PyGObject                          3.42.1
#### PyICU                              2.8.1
#### pyinotify                          0.9.6
#### PyJWT                              2.3.0
#### pylint                             4.0.4
#### pymacaroons                        0.13.0
#### PyNaCl                             1.5.0
#### PyOpenGL                           3.1.10
#### pyparsing                          2.4.7
#### pyparted                           3.11.7
#### PyQt5                              5.15.11
#### PyQt5-Qt5                          5.15.14
#### PyQt5_sip                          12.15.0
#### pyqtgraph                          0.13.7
#### PyQtWebEngine                      5.15.7
#### PyQtWebEngine-Qt5                  5.15.14
#### pyRFC3339                          1.1
#### pyrr                               0.10.3
#### pyrsistent                         0.18.1
#### pyserial                           3.5
#### PySide6                            6.10.1
#### PySide6_Addons                     6.10.1
#### PySide6_Essentials                 6.10.1
#### python-apt                         2.4.0+ubuntu4.1
#### python-dateutil                    2.9.0.post0
#### python-debian                      0.1.43+ubuntu1.1
#### python-dotenv                      0.19.2
#### python-gnupg                       0.4.8
#### python-json-logger                 2.0.7
#### python-lsp-jsonrpc                 1.1.2
#### python-lsp-server                  1.14.0
#### python-magic                       0.4.24
#### python-xlib                        0.29
#### pythonfmu                          0.6.3
#### pythonfmu3                         0.1.15
#### pytokens                           0.3.0
#### pytoolconfig                       1.3.1
#### pytz                               2022.1
#### pyxattr                            0.7.2
#### pyxdg                              0.27
#### PyYAML                             5.4.1
#### pyzmq                              26.2.0
#### qrcode                             7.3.1
#### referencing                        0.35.1
#### reportlab                          3.6.8
#### requests                           2.32.3
#### requests-file                      1.5.1
#### retrying                           1.3.4
#### rfc3339-validator                  0.1.4
#### rfc3986-validator                  0.1.1
#### roman                              3.3
#### rope                               1.14.0
#### rpds-py                            0.20.0
#### scipy                              1.14.1
#### SecretStorage                      3.3.1
#### Send2Trash                         1.8.3
#### setproctitle                       1.2.2
#### setuptools                         59.6.0
#### shiboken6                          6.10.1
#### six                                1.16.0
#### sniffio                            1.3.1
#### snowballstemmer                    3.0.1
#### soupsieve                          2.3.1
#### ssh-import-id                      5.11
#### stack-data                         0.6.3
#### systemd-python                     234
#### tenacity                           9.0.0
#### terminado                          0.18.1
#### texttable                          1.6.4
#### thonny                             3.3.14
#### tinycss2                           1.3.0
#### tldextract                         3.1.2
#### toml                               0.10.2
#### tomli                              2.0.1
#### tomlkit                            0.13.3
#### toolz                              0.12.1
#### tornado                            6.4.1
#### traitlets                          5.14.3
#### ttystatus                          0.38
#### typed-ast                          1.4.3
#### types-aiofiles                     0.1
#### types-annoy                        1.17
#### types-appdirs                      1.4
#### types-atomicwrites                 1.4
#### types-aws-xray-sdk                 2.8
#### types-babel                        2.9
#### types-backports-abc                0.5
#### types-backports.ssl-match-hostname 3.7
#### types-beautifulsoup4               4.10
#### types-bleach                       4.1
#### types-boto                         2.49
#### types-braintree                    4.11
#### types-cachetools                   4.2
#### types-caldav                       0.8
#### types-certifi                      2020.4
#### types-characteristic               14.3
#### types-chardet                      4.0
#### types-click                        7.1
#### types-click-spinner                0.1
#### types-colorama                     0.4
#### types-commonmark                   0.9
#### types-contextvars                  0.1
#### types-croniter                     1.0
#### types-cryptography                 3.3
#### types-dataclasses                  0.1
#### types-dateparser                   1.0
#### types-DateTimeRange                0.1
#### types-decorator                    0.1
#### types-Deprecated                   1.2
#### types-docopt                       0.6
#### types-docutils                     0.17
#### types-editdistance                 0.5
#### types-emoji                        1.2
#### types-entrypoints                  0.3
#### types-enum34                       1.1
#### types-filelock                     3.2
#### types-first                        2.0
#### types-Flask                        1.1
#### types-freezegun                    1.1
#### types-frozendict                   0.1
#### types-futures                      3.3
#### types-html5lib                     1.1
#### types-httplib2                     0.19
#### types-humanfriendly                9.2
#### types-ipaddress                    1.0
#### types-itsdangerous                 1.1
#### types-JACK-Client                  0.1
#### types-Jinja2                       2.11
#### types-jmespath                     0.10
#### types-jsonschema                   3.2
#### types-Markdown                     3.3
#### types-MarkupSafe                   1.1
#### types-mock                         4.0
#### types-mypy-extensions              0.4
#### types-mysqlclient                  2.0
#### types-oauthlib                     3.1
#### types-orjson                       3.6
#### types-paramiko                     2.7
#### types-Pillow                       8.3
#### types-polib                        1.1
#### types-prettytable                  2.1
#### types-protobuf                     3.17
#### types-psutil                       5.8
#### types-psycopg2                     2.9
#### types-pyaudio                      0.2
#### types-pycurl                       0.1
#### types-pyfarmhash                   0.2
#### types-Pygments                     2.9
#### types-PyMySQL                      1.0
#### types-pyOpenSSL                    20.0
#### types-pyRFC3339                    0.1
#### types-pysftp                       0.2
#### types-pytest-lazy-fixture          0.6
#### types-python-dateutil              2.9.0.20240821
#### types-python-gflags                3.1
#### types-python-nmap                  0.6
#### types-python-slugify               5.0
#### types-pytz                         2021.1
#### types-pyvmomi                      7.0
#### types-PyYAML                       5.4
#### types-redis                        3.5
#### types-requests                     2.25
#### types-retry                        0.9
#### types-selenium                     3.141
#### types-Send2Trash                   1.8
#### types-setuptools                   57.4
#### types-simplejson                   3.17
#### types-singledispatch               3.7
#### types-six                          1.16
#### types-slumber                      0.7
#### types-stripe                       2.59
#### types-tabulate                     0.8
#### types-termcolor                    1.1
#### types-toml                         0.10
#### types-toposort                     1.6
#### types-ttkthemes                    3.2
#### types-typed-ast                    1.4
#### types-tzlocal                      0.1
#### types-ujson                        0.1
#### types-vobject                      0.9
#### types-waitress                     0.1
#### types-Werkzeug                     1.0
#### types-xxhash                       2.0
#### typing_extensions                  4.12.2
#### tzdata                             2025.3
#### ubuntu-drivers-common              0.0.0
#### ufw                                0.36.1
#### ujson                              5.11.0
#### Unidecode                          1.3.3
#### uri-template                       1.3.0
#### urllib3                            1.26.5
#### uv                                 0.9.26
#### vboxapi                            1.0
#### vulkan                             1.3.275.1
#### wadllib                            1.3.6
#### wcwidth                            0.2.13
#### webcolors                          24.8.0
#### webencodings                       0.5.1
#### websocket-client                   1.8.0
#### websockets                         9.1
#### Werkzeug                           3.0.4
#### whatthepatch                       1.0.7
#### wheel                              0.37.1
#### wrapt                              1.13.3
#### wxPython                           4.0.7
#### xdg                                5
#### xkit                               0.0.0
#### xlrd                               1.2.0
#### yapf                               0.43.0
#### yt-dlp                             2022.4.8
#### zipp                               1.0.0